version: "3.9"
services:
  db:
    image: postgres:15
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: woozyBoi0!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forest-app
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:woozyBoi0!@db:5432/postgres
      SECRET_KEY: your-very-secret-key
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: 